name: clean_getx
description: A simple way to apply best practices with flutter and GetX
version: 0.0.1
homepage: https://github.com/elbeicktalat/clean_getx

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  internet_connection_checker: ^1.0.0+1
  meta: ^1.11.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0